name: bat
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
  frontend:
    image: node:22
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend/testing
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - GO_ENV=development
    depends_on:
      - frontend